@extends('layouts.app')
@section('title', $project->title)
@section('content')
<section class="page shell">
<a class="back" href="{{ route('projects.index') }}">← All projects</a>
<div class="project-hero reveal" style="--accent:{{ $project->color }}"><div><span class="eyebrow"><i></i> Active project</span><h1>{{ $project->title }}</h1><p>{{ $project->description ?: 'Everything this project needs, all in one place.' }}</p><div class="project-meta">@if($project->due_date)<span>◷ Due {{ $project->due_date->format('F j, Y') }}</span>@endif<span>✓ {{ $counts['done'] ?? 0 }} complete</span></div></div><div class="head-actions"><a class="btn secondary" href="{{ route('projects.edit',$project) }}">Edit project</a><a class="btn" href="{{ route('projects.tasks.create',$project) }}">＋ Add task</a></div></div>
<div class="task-toolbar"><div class="filters"><span>View</span>@foreach(['all'=>'All','todo'=>'To Do','in_progress'=>'In Progress','done'=>'Done'] as $key=>$label)<a class="{{ $status===$key?'active':'' }}" href="{{ route('projects.show',[$project,'status'=>$key]) }}">{{ $label }} @if($key!=='all')<b>{{ $counts[$key] ?? 0 }}</b>@endif</a>@endforeach</div><span class="task-total">{{ $tasks->count() }} {{ Str::plural('task',$tasks->count()) }}</span></div>
@if($tasks->isEmpty())<div class="empty compact"><span>○</span><h2>{{ $status === 'all' ? 'A beautifully blank slate.' : 'Nothing in this view.' }}</h2><p>{{ $status === 'all' ? 'Add the first task and give this project some momentum.' : 'Try another filter, or add a new task.' }}</p><a href="{{ route('projects.tasks.create',$project) }}" class="btn">Add a task →</a></div>
@else<div class="task-list">@foreach($tasks as $task)<article class="task-row reveal"><span class="status-dot {{ $task->status }}">{{ $task->status==='done'?'✓':'' }}</span><a class="task-main" href="{{ route('projects.tasks.show',[$project,$task]) }}"><h3 class="{{ $task->status==='done'?'struck':'' }}">{{ $task->title }}</h3><p>{{ $task->description ? Str::limit($task->description,100) : 'No additional notes' }}</p></a><span class="priority {{ $task->priority }}">{{ ucfirst($task->priority) }}</span><span class="due">{{ $task->due_date ? $task->due_date->format('M j') : 'No date' }}</span><a class="icon-btn" href="{{ route('projects.tasks.edit',[$project,$task]) }}" aria-label="Edit">✎</a></article>@endforeach</div>@endif
<div class="danger-zone"><div><h3>Project settings</h3><p>Deleting a project also removes all of its tasks.</p></div><form method="POST" action="{{ route('projects.destroy',$project) }}" data-confirm="Delete this project and every task inside it?">@csrf @method('DELETE')<button class="danger-btn">Delete project</button></form></div>
</section>
@endsection
